package com.tuproyecto.imc.view;

import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author Elias Pérez Arroyo
 */
public class Calculado_Vista extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculado_Vista.class.getName());

    /**
     * Creates new form Calculado_Vista
     */
    public Calculado_Vista() {
        initComponents();
    }
    
    public String getPeso() {      
        return txtPeso.getText().trim();
    }
    
    public String getAltura() {      
        return txtAltura.getText().trim();
    }
    
    public JButton getBtnCalcular(){
        return btnCalcular;
    }
    
    public void setCalculo(String resultado){
        lblCalculo.setText(resultado);
    }
    
    public void setClasiDePeso(String clasificacion){
        lblClasiDePeso.setText(clasificacion);
    }
    
    public void mostrarErrorDatos(byte codigoError){
        lblError.setForeground(Color.red);
        if(codigoError==1){
            lblError.setText("Dato introducido en Tu Peso no es válido");
            txtPeso.setText("");
            txtPeso.requestFocusInWindow();
        }else{
            lblError.setText("Dato introducido en Tu Altura no es válido");
            txtAltura.setText("");
            txtAltura.requestFocusInWindow();
        }
                  
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIzq = new javax.swing.JPanel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        lblTuAltura = new javax.swing.JLabel();
        lblTuPeso = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblKg = new javax.swing.JLabel();
        lblCm = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        pnlDrcha = new javax.swing.JPanel();
        lblTuIMCes = new javax.swing.JLabel();
        lblCalculo = new javax.swing.JLabel();
        lblClasiDePeso = new javax.swing.JLabel();
        lblClasiResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPeso.setPreferredSize(new java.awt.Dimension(180, 22));
        txtPeso.addActionListener(this::txtPesoActionPerformed);

        txtAltura.addActionListener(this::txtAlturaActionPerformed);

        lblTuAltura.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTuAltura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTuAltura.setText("TU ALTURA:");

        lblTuPeso.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTuPeso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTuPeso.setText("TU PESO:");

        btnCalcular.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCalcular.setText("CALCULA");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        lblKg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKg.setText("kg");

        lblCm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCm.setText("cm");

        lblError.setText("jLabel1");

        javax.swing.GroupLayout pnlIzqLayout = new javax.swing.GroupLayout(pnlIzq);
        pnlIzq.setLayout(pnlIzqLayout);
        pnlIzqLayout.setHorizontalGroup(
            pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTuPeso)
                    .addComponent(lblTuAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIzqLayout.createSequentialGroup()
                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIzqLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblKg))
                            .addGroup(pnlIzqLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnCalcular))))
                    .addGroup(pnlIzqLayout.createSequentialGroup()
                        .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCm)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlIzqLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlIzqLayout.setVerticalGroup(
            pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIzqLayout.createSequentialGroup()
                .addGroup(pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIzqLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnCalcular)
                        .addGap(3, 3, 3)
                        .addGroup(pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTuAltura)
                            .addComponent(lblCm)))
                    .addGroup(pnlIzqLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(pnlIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTuPeso)
                            .addComponent(lblKg))))
                .addGap(18, 18, 18)
                .addComponent(lblError)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        lblTuIMCes.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        lblTuIMCes.setText("TU IMC ES");

        lblCalculo.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        lblCalculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalculo.setText("25");

        lblClasiDePeso.setText("Clasificación de peso:");

        lblClasiResultado.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblClasiResultado.setText("Exceso de peso");

        javax.swing.GroupLayout pnlDrchaLayout = new javax.swing.GroupLayout(pnlDrcha);
        pnlDrcha.setLayout(pnlDrchaLayout);
        pnlDrchaLayout.setHorizontalGroup(
            pnlDrchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrchaLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(pnlDrchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDrchaLayout.createSequentialGroup()
                        .addComponent(lblClasiDePeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClasiResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDrchaLayout.createSequentialGroup()
                        .addComponent(lblCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDrchaLayout.createSequentialGroup()
                        .addComponent(lblTuIMCes)
                        .addGap(187, 187, 187))))
        );
        pnlDrchaLayout.setVerticalGroup(
            pnlDrchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrchaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTuIMCes)
                .addGap(18, 18, 18)
                .addComponent(lblCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlDrchaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasiDePeso)
                    .addComponent(lblClasiResultado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDrcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlDrcha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlturaActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculado_Vista().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel lblCalculo;
    private javax.swing.JLabel lblClasiDePeso;
    private javax.swing.JLabel lblClasiResultado;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblKg;
    private javax.swing.JLabel lblTuAltura;
    private javax.swing.JLabel lblTuIMCes;
    private javax.swing.JLabel lblTuPeso;
    private javax.swing.JPanel pnlDrcha;
    private javax.swing.JPanel pnlIzq;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
